
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlrreibtmfchoiaymtkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5scnJlaWJ0bWZjaG9pYXltdGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDg3ODQsImV4cCI6MjA1OTQyNDc4NH0.voeCyRLYGi0IZBZQrhNxUI4HkfZPlM7hqSl26KZmwKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
